/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame */

#ifndef _Included_com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame
#define _Included_com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anhuioss_crowdroid_util_RecordVoiceToMp3Lame_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
